title: "ZeroG Documentation"
tagline: Documentation for ZeroG printers
description: ZeroG Official Documentation
logo: "/assets/images/logo-zerog.svg"
baseurl: ""
markdown: kramdown
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
color_scheme: "zerog"
search_enabled: true
timezone: Europe/Amsterdam
aux_links:
  "GitHub":
    - "//github.com/ZeroGDesign/docs"
  "Ko-Fi":
    - "https://ko-fi.com/zerog"
aux_links_new_tab: true

ga_tracking: G-6NEWMMGBTW
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)


nav_external_links:
  - title: Join Our Discord
    url: https://discord.gg/zerog
    hide_icon: false # set to true to hide the external link icon - defaults to false